#!/usr/bin/env bash
set -euo pipefail

input=$(cat)

agent_id=$(echo "$input" | jq -r '.agent_id // empty')
[[ -z "$agent_id" ]] || exit 0

prompt=$(echo "$input" | jq -r '.prompt // empty')
transcript=$(echo "$input" | jq -r '.transcript_path // empty')
session_id=$(echo "$input" | jq -r '.session_id // empty')

# Explicit <title> tag always wins, even over existing titles
if [[ "$prompt" =~ \<title\>([^<]+)\</title\> ]]; then
  title="${BASH_REMATCH[1]}"
  jq -n --arg t "$title" '{hookSpecificOutput: {hookEventName: "UserPromptSubmit", sessionTitle: $t}}'
  exit 0
fi

# Already titled — don't overwrite with auto-generated title
if [[ -n "$transcript" && -f "$transcript" ]]; then
  if jq -e 'select(.type == "custom-title")' "$transcript" > /dev/null 2>&1; then
    exit 0
  fi
fi

# Title generated by Stop hook (temp file signal)
title_file="/tmp/claude-session-titles/${session_id}.txt"
if [[ -f "$title_file" ]]; then
  title=$(<"$title_file")
  rm -f "$title_file"
  if [[ -n "$title" ]]; then
    jq -n --arg t "$title" '{hookSpecificOutput: {hookEventName: "UserPromptSubmit", sessionTitle: $t}}'
    exit 0
  fi
fi

exit 0
