---
- name: "Unlink {{ conflict.key }}"
  ansible.builtin.command:
    argv: ["brew", "unlink", "{{ conflict.key }}"]
  changed_when: false
  failed_when: false

- name: "Upgrade keg-only formulas ({{ conflict.value | join(', ') }})"
  ansible.builtin.command:
    argv: ["brew", "upgrade", "{{ homebrew_keg_formula }}"]
  loop: "{{ conflict.value }}"
  loop_control:
    loop_var: homebrew_keg_formula
  register: homebrew_keg_upgrade_result
  changed_when: "'Pouring' in homebrew_keg_upgrade_result.stdout"
  failed_when: homebrew_keg_upgrade_result.rc != 0 and 'already installed' not in homebrew_keg_upgrade_result.stderr

- name: "Unlink keg-only formulas ({{ conflict.value | join(', ') }})"
  ansible.builtin.command:
    argv: ["brew", "unlink", "{{ homebrew_keg_formula }}"]
  loop: "{{ conflict.value }}"
  loop_control:
    loop_var: homebrew_keg_formula
  changed_when: false
  failed_when: false

- name: "Re-link {{ conflict.key }}"
  ansible.builtin.command:
    argv: ["brew", "link", "{{ conflict.key }}"]
  changed_when: false
  failed_when: false
