---
- name: Check if Forge Code is installed
  ansible.builtin.stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/bin/forge"
  register: forge_code_binary

- name: Download Forge Code install script
  when: not forge_code_binary.stat.exists
  ansible.builtin.get_url:
    url: https://forgecode.dev/cli
    dest: /tmp/forge-code-install.sh
    mode: "0755"

- name: Run Forge Code install script
  when: not forge_code_binary.stat.exists
  ansible.builtin.command:
    cmd: /tmp/forge-code-install.sh
    creates: "{{ ansible_facts['env']['HOME'] }}/.local/bin/forge"
