---
# NSGlobalDomain settings

- name: Configure NSGlobalDomain - show all files
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present

- name: Configure NSGlobalDomain - show all extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    state: present

- name: Configure NSGlobalDomain - always show scroll bars
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: Always
    state: present

- name: Configure NSGlobalDomain - disable auto-capitalization
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
    state: present

- name: Configure NSGlobalDomain - disable smart dashes
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: Configure NSGlobalDomain - disable auto-period
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: Configure NSGlobalDomain - disable smart quotes
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: Configure NSGlobalDomain - disable auto-spelling correction
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
    state: present

- name: Configure NSGlobalDomain - expand save panel by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
    state: present

- name: Configure NSGlobalDomain - expand save panel by default (2)
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode2
    type: bool
    value: true
    state: present
