import = ["fnox.toml"]

[secrets]
CLOUDFLARE_TOKEN = { provider = "agent", value = "op://agent/5cimwvc3mbcr6cikiv3wcmhekm/tunnel/token" }
CLI_PROXY_API_ADMIN_KEY = { provider = "agent", value = "op://agent/vf3jsatixwtzauzoebt66xkiqe/admin apikey" }
GEMINI_API_KEY = { provider = "agent", value = "op://agent/czcysdu5pyr5d7x2ztguqpftv4/credential" }
XGS_PON_PASSWORD = { provider = "agent", value = "op://agent/fybwsg6a6cfbq5bvkg7y2ehbgy/password" }
NEXTDNS_API_KEY = { provider = "agent", value = "op://agent/db7ivx7ja3sc74k4yml5qrg4ra/apikey" }
DDCLIENT_GITHUB_PAT = { provider = "agent", value = "op://agent/zid4qeby3vbv6wgcqkon2zxyxm/credential" }
GHOST_DB_PASSWORD = { provider = "agent", value = "op://agent/r3krzpluypr6dtsuoza5p7xafm/ghostuser password" }
GHOST_MYSQL_ROOT_PASSWORD = { provider = "agent", value = "op://agent/r3krzpluypr6dtsuoza5p7xafm/root password" }
GHOST_MAIL_AUTH_PASS = { provider = "agent", value = "op://agent/r3krzpluypr6dtsuoza5p7xafm/auth password" }
HOMEPAGE_OVERSEERR_API_KEY = { provider = "agent", value = "op://agent/llvkionb6paszgyawy2utzpfoe/apikey" }
HOMEPAGE_PLEX_API_KEY = { provider = "agent", value = "op://agent/fwi425e6pshd3226h5ved6g4ha/x-plex-token" }
PLEX_CLAIM_TOKEN = { provider = "agent", value = "op://agent/fwi425e6pshd3226h5ved6g4ha/claim-token" }
QBITTORRENT_USERNAME = { provider = "agent", value = "op://agent/u7mtgl5vtxpisyndwkliwkv6ju/username" }
QBITTORRENT_PASSWORD = { provider = "agent", value = "op://agent/u7mtgl5vtxpisyndwkliwkv6ju/password" }
PROWLARR_API_KEY = { provider = "agent", value = "op://agent/v44vsx76b6hriwclevnwelhs6i/apikey" }
RADARR_API_KEY = { provider = "agent", value = "op://agent/sil4v5ljh7d52fam7s2nxdfddu/apikey" }
SONARR_API_KEY = { provider = "agent", value = "op://agent/oqqqt2eb5lbh4gjnxuo4jgmouu/apikey" }
TORRENT_WIREGUARD_PRIVATE_KEY = { provider = "agent", value = "op://agent/hyqqxr44mqyzudmu327t2aowpu/wireguard/private key" }
TORRENT_WIREGUARD_ADDRESS = { provider = "agent", value = "op://agent/hyqqxr44mqyzudmu327t2aowpu/wireguard/address" }
HARK_WEBHOOK_URL_POD042 = { provider = "agent", value = "op://agent/u3wmydm5i7fe3cgdxx6c7juhxq/add more/pod042 webhook url" }
HEALTHCHECKS_API_KEY = { provider = "agent", value = "op://agent/injsaejfgmueiievbdiuioggui/add more/api key" }
SAMBA_MEDIA_PASSWORD = { provider = "agent", value = "op://agent/rqdlvwpivnndduj4wyhxqwqa4a/password" }
RESTIC_B2_BUCKET = { provider = "agent", value = "op://agent/Backblaze/bucket" }
RESTIC_B2_KEY_ID = { provider = "agent", value = "op://agent/Backblaze/key id" }
RESTIC_B2_APPLICATION_KEY = { provider = "agent", value = "op://agent/Backblaze/applicationKey" }
RESTIC_REPOSITORY_PASSWORD = { provider = "agent", value = "op://agent/Backblaze/repository password" }
POD042_GIT_SSH_PRIVATE_KEY = { provider = "agent", value = "op://agent/xvusqt5rhadejhfjjp7crgyrp4/private key" }
POD042_GIT_SSH_PUBLIC_KEY = { provider = "agent", value = "op://agent/xvusqt5rhadejhfjjp7crgyrp4/public key" }
