---
all:
  children:
    openclaw_remote:
      hosts:
        openclaw-vm:
          ansible_host: 192.168.1.90
          ansible_user: thurstonsand
          ansible_python_interpreter: /usr/bin/python3
          ansible_become_password: "{{ lookup('env', 'OPENCLAW_BECOME_PASSWORD') }}"
    openclaw_local:
      hosts:
        openclaw-local:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          ansible_become_password: "{{ lookup('env', 'OPENCLAW_BECOME_PASSWORD') }}"
