#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# bringup.sh — bunker-rebuild Phase 3, new house.
# Network first, then the machine, then the reconcile. Machine stages run
# themselves; every stage is resumable. 2B drives the Debian install over the
# NetKVM console — this wizard tells you when to hand over.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.cutover-state"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"

TOTAL_STAGES=9

banner "Bunker bring-up — new house"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Network first (you wire, machine verifies)"
step "Install the UDMP where it lives now. Fiber → WAS-110 → UDMP WAN (SFP+)."
step "LAN switch + APs as before (photos from teardown stage 7)."
step "Join your laptop to the LAN (wifi or cable)."
pause "Wired and powered?"
say "Waiting for WAN (up to 10 min — the stick negotiates PON)..."
for i in $(seq 1 60); do
  if ping -c1 -t2 1.1.1.1 >/dev/null 2>&1; then say "internet is up."; break; fi
  sleep 10
  [[ $i == 60 ]] && { warn "no WAN after 10 min — check PON LED; see runbooks/xgs-pon-upgrade.md for stick access; call 2B."; exit 1; }
done
say "Stick health (optional, unauthenticated metrics):"
curl -sk --max-time 5 https://192.168.11.1/cgi-bin/luci/8311/metrics 2>/dev/null | head -c 200 || note "stick metrics unreachable — fine if WAN works"
write_env BRINGUP_WAN "$(date -u +%s)"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Rack the server (you)"
step "Server in place, power connected, LAN cable to the SAME switch port profile as before (trunk)."
step "Connect the GLKVM to the server (HDMI + USB) and to the LAN."
step "Power the server on."
ask KVM_URL "GLKVM web URL once it's on the LAN (e.g. http://192.168.1.x):"
note "creds: op item 'GLKVM' (agent vault)"
step "In the GLKVM UI: Virtual Media → mount scripts/debian-13-netinst.iso from this laptop."
write_env BRINGUP_KVM_URL "$KVM_URL"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "BIOS pass (2B drives via KVM, you watch)"
say "Hand the KVM URL to 2B. Settings to change:"
step "Intel VMD Controller: DISABLED (NVMe must appear as plain devices)"
step "Boot order: GLKVM virtual media (USB device) first for this boot; SATA SSD (the 448G) primary after"
step "AC Power Loss: power on (it's a server now, fully)"
step "Leave everything else alone."
pause "BIOS saved and rebooting into the USB installer?"
write_env BRINGUP_BIOS "done"

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Debian install (2B drives via KVM)"
say "2B drives the installer over the KVM. The choices, for the record:"
note "hostname pod042 · domain thurstons.house · user thurstonsand"
note "TARGET DISK: the 448G SATA SSD ONLY — never a pool member (4×14T, 2×1T NVMe)"
note "guided partitioning, whole disk, ext4, no swap partition question fights"
note "software selection: ssh server + standard utilities, NO desktop"
pause "Install finished and rebooted into Debian?"
ask NEW_IP "IP the new host got (shown on console login, or check UDMP clients):"
write_env BRINGUP_IP "$NEW_IP"

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Native landing zone (machine)"
say "Installing the operator key and converging the shared native mise target."
note "The workstation checkout must be clean, pushed, and on the revision intended for pod042."
mise -C "$REPO_ROOT" pod042:first-access "$NEW_IP" \
  || { warn "First access failed. Preserve the host and command output; do not run the retired Ansible playbook."; exit 1; }
ssh "thurstonsand@${NEW_IP}" 'sudo -n true && test -x /usr/local/bin/mise && test -d ~/code/ansiblonomicon/.git'
write_env BRINGUP_BOOTSTRAP "done"

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Pool validation, import, and rename (machine)"
say "Discovering exported pools through stable device identifiers."
ssh "thurstonsand@${NEW_IP}" 'sudo zpool import -d /dev/disk/by-id' || true
note "Required identities: capacity=8619294010601504858; performance=131852107186480998."
if ! confirm "Do both GUIDs and expected topologies appear above? Proceed with read-only validation?"; then
  warn "Stop. Do not import a pool by device letter."; exit 1
fi
ssh "thurstonsand@${NEW_IP}" 'set -eu
  sudo zpool import -f -N -o readonly=on -d /dev/disk/by-id 8619294010601504858
  sudo zpool status -P capacity
  sudo zfs list -H -t snapshot -o name capacity@pre-debian-20260905T050835Z
  sudo zpool export capacity
  sudo zpool import -f -N -o readonly=on -d /dev/disk/by-id 131852107186480998
  sudo zpool status -P performance
  sudo zfs list -H -t snapshot -o name performance@pre-debian-20260905T050835Z
  sudo zpool export performance'
if ! confirm "Are both pools ONLINE with no known data errors and both final snapshots present?"; then exit 1; fi
ssh "thurstonsand@${NEW_IP}" 'set -eu
  sudo zpool import -f -N -d /dev/disk/by-id 8619294010601504858 ark
  sudo zpool import -f -N -d /dev/disk/by-id 131852107186480998 black-box
  sudo zfs set mountpoint=/mnt/ark ark
  sudo zfs set mountpoint=/mnt/black-box black-box
  sudo zfs mount -a
  sudo test -s /etc/zfs/zpool.cache
  sudo zpool status -x'
write_env BRINGUP_POOLS "done"

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Native reconcile (machine)"
say "Converging the exact pushed revision through the shared workstation/host target."
python3 "$REPO_ROOT/scripts/pod042_reconcile.py" --host "$NEW_IP" \
  || { warn "Native reconciliation failed. Preserve its output and repair the declared resource before rerunning."; exit 1; }
ssh "thurstonsand@${NEW_IP}" 'sudo zpool status -x; sudo zfs list -H -o name,mountpoint,mounted ark ark/watch black-box black-box/docker'
write_env BRINGUP_RECONCILE "done"

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Verification battery (machine)"
FAIL=0
check() { if eval "$2"; then say "✓ $1"; else warn "✗ $1"; FAIL=1; fi; }
check "pools healthy"        "ssh thurstonsand@${NEW_IP} 'sudo zpool status -x' | grep -q 'all pools are healthy'"
check "QuickSync visible"    "ssh thurstonsand@${NEW_IP} 'ls /dev/dri/renderD128' >/dev/null 2>&1"
check "docker stacks up"     "[ \$(ssh thurstonsand@${NEW_IP} 'docker ps -q | wc -l') -ge 10 ]"
check "plex answering"       "ssh thurstonsand@${NEW_IP} 'curl -sf -o /dev/null -m 5 http://localhost:32400/identity'"
check "samba share"          "ssh thurstonsand@${NEW_IP} 'smbclient -L localhost -N 2>/dev/null | grep -q media'"
check "alerting heartbeat"   "ssh thurstonsand@${NEW_IP} 'systemctl is-active alerting-heartbeat.timer' | grep -q active"
say "smartd could not be tested in the rig (ConditionVirtualization=no) — verifying live:"
check "smartd running"       "ssh thurstonsand@${NEW_IP} 'systemctl is-active smartd' | grep -q active"
if [[ $FAIL == 0 ]]; then
  write_env BRINGUP_VERIFIED "$(date -u +%s)"
else
  warn "Failures above — 2B's problem now. The passing subset still works."
fi

# ── Stage 9 ───────────────────────────────────────────────────────────────
stage "Acceptance (you)"
step "Play something on Plex from the TV — confirm it transcodes (dashboard shows (hw))."
step "Finder → Network: mount the media share with user thurstonsand + op item 'Samba media (pod042)'."
step "Phone got the Hark heartbeat? (First one within 15 min.)"
note "Post-move queue (with 2B): ticket-10 dataset rebuild, caddy gateway + debridging,"
note "UDMP wipe + terraform, incus + pascal, ticket 17 purge, CONTEXT.md rewrite."
write_env BRINGUP_COMPLETE "$(date -u +%s)"

finish
