#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# teardown.sh — bunker-rebuild Phase 2, old house.
# Shuts the TrueNAS machine down clean and leaves it transportable no matter
# where this script stops. Machine stages run themselves; you do the physical.
# Resumable: state in .cutover-state beside this script. 2B stays on the line —
# if a stage fails, stop and report rather than improvising.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.cutover-state"
NAS_HOST="${NAS_HOST:-truenas}"

# Arguments are complete remote command strings supplied by this script.
# shellcheck disable=SC2029
run_nas() { ssh "$NAS_HOST" "$@"; }

TOTAL_STAGES=7

banner "Bunker teardown — old house"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight (machine)"
say "Verifying the NAS answers, the B2 backup exists, and nothing is on fire."
run_nas 'echo nas-ok' | grep -q nas-ok || { warn "NAS unreachable — fix before continuing"; exit 1; }
if run_nas 'docker ps --format "{{.Names}}" | wc -l' | grep -qE '[1-9]'; then
  say "docker stacks currently running: $(run_nas 'docker ps --format "{{.Names}}" | wc -l' | tr -d ' ')"
fi
say "Most recent B2 snapshot (must exist — premove-backup.sh ran 2026-08-21):"
note "verified snapshot a21e7e22 (28.997 GiB, checked + restore-diffed)"
if ! confirm "Backup evidence acceptable?"; then exit 1; fi
write_env TEARDOWN_PREFLIGHT "done"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Debian 13 netinst ISO (machine downloads — no USB needed)"
ISO="${SCRIPT_DIR}/debian-13-netinst.iso"
if [[ ! -f "$ISO" ]]; then
  say "Downloading the current Debian 13 amd64 netinst ISO..."
  curl -fL -o "$ISO" "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/$(curl -fsS https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/ | grep -oE 'debian-13[0-9.]*-amd64-netinst.iso' | head -1)"
fi
say "ISO ready at: $ISO ($(du -h "$ISO" | cut -f1))"
note "Install boots via the GLKVM's virtual-media mount at the new house —"
note "the ISO stays on this laptop; nothing to flash, nothing to pack."
write_env TEARDOWN_ISO "done"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "UDMP config backup (machine)"
say "Capturing the newest UniFi autobackup off the router."
mkdir -p "${SCRIPT_DIR}/../artifacts"
LATEST=$(ssh udmp 'ls -t /data/unifi/data/backup/autobackup/*.unf 2>/dev/null | head -1')
if [[ -n "$LATEST" ]]; then
  scp "udmp:${LATEST}" "${SCRIPT_DIR}/../artifacts/" && say "saved $(basename "$LATEST")"
  write_env TEARDOWN_UDMP_BACKUP "$(basename "$LATEST")"
else
  warn "No autobackup found — grab one from the UniFi UI (System → Backups) manually."
  pause "Done (or accepting the risk)?"
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Final safety snapshots (machine)"
STAMP="premove-final-$(date -u +%Y%m%dT%H%M%SZ)"
say "Recursive snapshot @${STAMP} on both pools via the middleware."
for DS in performance capacity; do
  if run_nas "midclt call zfs.snapshot.create '{\"dataset\": \"$DS\", \"name\": \"$STAMP\", \"recursive\": true}' >/dev/null"; then
    say "snapshotted ${DS}@${STAMP}"
  else
    warn "snapshot failed on ${DS} — investigate before continuing"
  fi
done
write_env TEARDOWN_FINAL_SNAP "$STAMP"

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Stop services (machine)"
say "Stopping every docker stack, VM, and file-sharing service. Downtime begins here."
if ! confirm "Take everything down now?"; then exit 1; fi
# Expansion belongs on the NAS, not this workstation.
# shellcheck disable=SC2016
run_nas 'docker stop $(docker ps -q) 2>/dev/null || true'
say "containers stopped: $(run_nas 'docker ps -q | wc -l' | tr -d ' ') still running (want 0)"
run_nas 'midclt call vm.query | python3 -c "import json,sys; [print(v[\"id\"], v[\"name\"], v[\"status\"][\"state\"]) for v in json.load(sys.stdin)]"' || true
step "If any VM above shows RUNNING, it gets stopped next."
# shellcheck disable=SC2016
run_nas 'midclt call vm.query | python3 -c "import json,sys; [print(v[\"id\"]) for v in json.load(sys.stdin) if v[\"status\"][\"state\"]==\"RUNNING\"]" | while read -r id; do midclt call vm.poweroff "$id"; done' || true
run_nas 'midclt call service.stop cifs >/dev/null; midclt call service.stop nfs >/dev/null'
write_env TEARDOWN_SERVICES_STOPPED "$(date -u +%s)"

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Export pools and shut down (machine)"
say "Exporting both pools cleanly before shutdown."
warn "Any shell whose current directory is inside a pool can block export."
if ! confirm "Export capacity and performance now?"; then exit 1; fi
run_nas 'cd / && sudo zpool export capacity && sudo zpool export performance'
say "Both exports succeeded. The Debian import may still require -f because the host identity changes."
warn "After this, the machine is dark until the new house."
if ! confirm "Shut the NAS down NOW?"; then exit 1; fi
run_nas 'sudo shutdown -h now' 2>/dev/null || run_nas 'midclt call system.shutdown "{}"' 2>/dev/null || true
say "Sent. Wait for fans/LEDs to stop before pulling power."
write_env TEARDOWN_SHUTDOWN "$(date -u +%s)"

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Pack (you)"
step "Power off + unplug: NAS, UDMP, WAS-110 stick, NetKVM, switch."
step "Photograph the rear cabling of the NAS and UDMP before unplugging."
step "The WAS-110 travels padded — it is the internet."
step "Do NOT separate drives from the chassis; they travel installed."
note "At the new house: run bringup.sh. It starts with the network, not the server."
write_env TEARDOWN_COMPLETE "$(date -u +%s)"

finish
