---
- name: Check if opencode is installed
  ansible.builtin.stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.opencode/bin/opencode"
  register: opencode_binary_status

- name: Download opencode install script
  when: not opencode_binary_status.stat.exists
  ansible.builtin.get_url:
    url: https://opencode.ai/install
    dest: /tmp/opencode-install.sh
    mode: "0755"

- name: Run opencode install script
  when: not opencode_binary_status.stat.exists
  ansible.builtin.command:
    cmd: /tmp/opencode-install.sh
    creates: "{{ ansible_facts['env']['HOME'] }}/.opencode/bin/opencode"
