import collections.abc as c
import typing as t
from _typeshed import Incomplete
from ansible.inventory.group import Group

__all__ = ['Host']

class Host:
    base_type: Incomplete
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...
    vars: dict[str, t.Any]
    groups: list[Group]
    name: str
    address: str
    implicit: bool
    def __init__(self, name: str, port: int | str | None = None, gen_uuid: bool = True) -> None: ...
    def get_name(self) -> str: ...
    def populate_ancestors(self, additions: c.Iterable[Group] | None = None) -> None: ...
    def add_group(self, group: Group) -> bool: ...
    def remove_group(self, group: Group) -> bool: ...
    def set_variable(self, key: str, value: t.Any) -> None: ...
    def get_groups(self) -> list[Group]: ...
    def get_magic_vars(self) -> dict[str, t.Any]: ...
    def get_vars(self) -> dict[str, t.Any]: ...
