---
motd_user: "{{ ansible_user_id }}"
motd_home: "{{ ansible_facts['env']['HOME'] }}"
motd_bin_dir: "{{ motd_home }}/.local/bin"
motd_cache_dir: "{{ motd_home }}/.cache"

motd_openclaw_enabled: "{{ 'openclaw' in npm_global_packages }}"
