#!/usr/bin/env python3
"""Deploy hooks Worker via Wrangler with secret management.

Secrets are read from .dev.vars (generated by direnv).
Use --force-secret/-f to update secrets even if they exist.
"""

import json
from pathlib import Path
import subprocess
import sys

from dotenv import dotenv_values, load_dotenv

ROOT_DIR = Path(__file__).parent.parent
WORKER_DIR = ROOT_DIR / "wrangler" / "hooks"
DEV_VARS = WORKER_DIR / ".dev.vars"
ROOT_ENV = ROOT_DIR / ".env"


def get_existing_secrets() -> set[str]:
    result = subprocess.run(
        ["wrangler", "secret", "list", "--format", "json"],
        cwd=WORKER_DIR,
        capture_output=True,
        text=True,
        check=True,
    )
    return {s["name"] for s in json.loads(result.stdout)}


def main(force_secret: bool = False) -> int:
    if not DEV_VARS.exists():
        print(
            f"Error: {DEV_VARS} not found. Run 'poe init-secrets' first.",
            file=sys.stderr,
        )
        return 1

    if ROOT_ENV.exists():
        load_dotenv(ROOT_ENV)

    print("Deploying hooks worker...")
    subprocess.run(["wrangler", "deploy"], cwd=WORKER_DIR, check=True)

    print("\nChecking secrets...")
    secrets = {k: v for k, v in dotenv_values(DEV_VARS).items() if v is not None}
    existing = get_existing_secrets()

    for name, value in secrets.items():
        if name in existing:
            if force_secret:
                print(f"Updating {name} secret (-f)...")
                subprocess.run(
                    ["wrangler", "secret", "put", name],
                    cwd=WORKER_DIR,
                    input=value,
                    text=True,
                    check=True,
                )
            else:
                print(f"{name} secret already exists (use -f to update)")
        else:
            print(f"Creating {name} secret...")
            subprocess.run(
                ["wrangler", "secret", "put", name],
                cwd=WORKER_DIR,
                input=value,
                text=True,
                check=True,
            )

    print("\nDone! Worker deployed to https://hooks.thurstons.house")
    return 0


if __name__ == "__main__":
    sys.exit(main())
