-- Generated by the Mouse panel plugin (io.github.wouldja.mouse). Use the panel to edit.
hl.config({
  input = {
    sensitivity = 0.20,
    accel_profile = "adaptive",
    natural_scroll = true,
    scroll_factor = 1.00,
    left_handed = false,
    touchpad = {
      natural_scroll = true,
      scroll_factor = 0.48,
      disable_while_typing = true,
      tap_to_click = true,
      clickfinger_behavior = true,
    },
  },
})
