from _typeshed import Incomplete
from ansible.playbook.base import Base
from ansible.playbook.collectionsearch import CollectionSearch
from ansible.playbook.conditional import Conditional
from ansible.playbook.delegatable import Delegatable
from ansible.playbook.notifiable import Notifiable
from ansible.playbook.taggable import Taggable

__all__ = ['Task']

class Task(Base, Conditional, Taggable, CollectionSearch, Notifiable, Delegatable):
    args: Incomplete
    action: Incomplete
    async_val: Incomplete
    changed_when: Incomplete
    delay: Incomplete
    failed_when: Incomplete
    loop: Incomplete
    loop_control: Incomplete
    poll: Incomplete
    register: Incomplete
    retries: Incomplete
    until: Incomplete
    loop_with: Incomplete
    implicit: bool
    def __init__(self, block=None, role=None, task_include=None) -> None: ...
    @property
    def resolved_action(self) -> str | None: ...
    def get_name(self, include_role_fqcn: bool = True): ...
    @staticmethod
    def load(data, block=None, role=None, task_include=None, variable_manager=None, loader=None): ...
    def preprocess_data(self, ds): ...
    def post_validate(self, templar) -> None: ...
    def get_vars(self): ...
    def get_include_params(self): ...
    def copy(self, exclude_parent: bool = False, exclude_tasks: bool = False) -> Task: ...
    def set_loader(self, loader) -> None: ...
    def all_parents_static(self): ...
    def get_first_parent_include(self): ...
    def get_play(self): ...
    def dump_attrs(self): ...
    def from_attrs(self, attrs) -> None: ...
