from typing import Any

class Post:
    content: str
    metadata: dict[str, Any]

    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self) -> list[str]: ...

def load(fd: str | Any) -> Post: ...
def loads(text: str) -> Post: ...
def dump(post: Post, fd: Any) -> None: ...
def dumps(post: Post) -> str: ...
