# Gruvbox dark theme
set -g window-style "bg=#1d2021"
set -g window-active-style "bg=#1d2021"
set -g status-style "bg=#3c3836,fg=#a89984,nobold,noitalics,nounderscore"
set -g status-left-length 80
set -g status-right-length 80
set -g status-left '#[bg=#a89984,fg=#282828,bold,noitalics,nounderscore] #{s|^ide-(.+)-[a-f0-9]+$|\1|:session_name} #[bg=#504945,fg=#a89984,nobold,noitalics,nounderscore] '
set -g window-status-separator '#[bg=#504945,fg=#504945]  '
set -g window-status-format '#[bg=#504945,fg=#928374,nobold,noitalics,nounderscore]#W#[bg=#504945]#{?window_end_flag, ,}#[bg=#3c3836,fg=#504945,nobold,noitalics,nounderscore]#{?window_end_flag,,}'
set -g window-status-current-format '#[bg=#504945,fg=#fabd2f,nobold,noitalics,nounderscore]#W#[bg=#504945]#{?window_end_flag, ,}#[bg=#3c3836,fg=#504945,nobold,noitalics,nounderscore]#{?window_end_flag,,}'
set -g status-right '#[bg=#3c3836,fg=#a89984,nobold,noitalics,nounderscore]#[bg=#a89984,fg=#282828,bold,noitalics,nounderscore] #h '
