# Gruvbox light status bar theme
set -g status-style "bg=#ebdbb2,fg=#7c6f64,nobold,noitalics,nounderscore"
set -g status-left-length 80
set -g status-right-length 80
set -g status-left '#[bg=#7c6f64,fg=#f9f5d7,bold,noitalics,nounderscore] #{s|^ide-(.+)-[a-f0-9]+$|\1|:session_name} #[bg=#d5c4a1,fg=#7c6f64,nobold,noitalics,nounderscore] '
set -g window-status-separator '#[bg=#d5c4a1,fg=#d5c4a1]  '
set -g window-status-format '#[bg=#d5c4a1,fg=#928374,nobold,noitalics,nounderscore]#W#[bg=#d5c4a1]#{?window_end_flag, ,}#[bg=#ebdbb2,fg=#d5c4a1,nobold,noitalics,nounderscore]#{?window_end_flag,,}'
set -g window-status-current-format '#[bg=#d5c4a1,fg=#b57614,nobold,noitalics,nounderscore]#W#[bg=#d5c4a1]#{?window_end_flag, ,}#[bg=#ebdbb2,fg=#d5c4a1,nobold,noitalics,nounderscore]#{?window_end_flag,,}'
set -g status-right '#[bg=#ebdbb2,fg=#7c6f64,nobold,noitalics,nounderscore]#[bg=#7c6f64,fg=#f9f5d7,bold,noitalics,nounderscore] #h '
