from ansible import context as context
from ansible.executor.task_result import CallbackTaskResult as CallbackTaskResult
from ansible.playbook.task_include import TaskInclude as TaskInclude
from ansible.plugins.callback import CallbackBase as CallbackBase
from ansible.utils.color import colorize as colorize, hostcolor as hostcolor
from ansible.utils.fqcn import add_internal_fqcns as add_internal_fqcns

DOCUMENTATION: str

class CallbackModule(CallbackBase):
    CALLBACK_VERSION: float
    CALLBACK_TYPE: str
    CALLBACK_NAME: str
    def __init__(self) -> None: ...
    def v2_runner_on_failed(self, result: CallbackTaskResult, ignore_errors: bool = False) -> None: ...
    def v2_runner_on_ok(self, result: CallbackTaskResult) -> None: ...
    def v2_runner_on_skipped(self, result: CallbackTaskResult) -> None: ...
    def v2_runner_on_unreachable(self, result: CallbackTaskResult) -> None: ...
    def v2_playbook_on_no_hosts_matched(self) -> None: ...
    def v2_playbook_on_no_hosts_remaining(self) -> None: ...
    def v2_playbook_on_task_start(self, task, is_conditional) -> None: ...
    def v2_playbook_on_handler_task_start(self, task) -> None: ...
    def v2_runner_on_start(self, host, task) -> None: ...
    def v2_playbook_on_play_start(self, play) -> None: ...
    def v2_on_file_diff(self, result: CallbackTaskResult) -> None: ...
    def v2_runner_item_on_ok(self, result: CallbackTaskResult) -> None: ...
    def v2_runner_item_on_failed(self, result: CallbackTaskResult) -> None: ...
    def v2_runner_item_on_skipped(self, result: CallbackTaskResult) -> None: ...
    def v2_playbook_on_include(self, included_file) -> None: ...
    def v2_playbook_on_stats(self, stats) -> None: ...
    def v2_playbook_on_start(self, playbook) -> None: ...
    def v2_runner_retry(self, result: CallbackTaskResult) -> None: ...
    def v2_runner_on_async_poll(self, result: CallbackTaskResult) -> None: ...
    def v2_runner_on_async_ok(self, result: CallbackTaskResult) -> None: ...
    def v2_runner_on_async_failed(self, result: CallbackTaskResult) -> None: ...
    def v2_playbook_on_notify(self, handler, host) -> None: ...
